[tool.poetry]
name = "mistion"
version = "0.3.5"
description = "Ionosphere simulation for the MIST project"
authors = ["lap1dem <vadym.bidula@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/lap1dem/mist_ion"
repository = "https://github.com/lap1dem/mist_ion"
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = ">=3.7, <3.10"
h5py = "^3.4.0"
iri2016 = "^1.11.1"
pymap3d = "^2.7.2"
tqdm = "^4.62.3"
mpi4py = "^3.1.2"
scipy = "^1.7"
matplotlib = "^3.5.1"


[tool.poetry.dev-dependencies]
jupyter = "^1.0.0"
basemap = "^1.3.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
